user_dec = input("Enter decimal number:")
str_to_int = int(user_dec)
binary_num = bin(str_to_int)
hex_num = hex(str_to_int)
oct_num = oct(str_to_int)
print("Binary num: ", binary_num, "\nHex num: ", hex_num, "\nOct num:", oct_num)